#!/usr/bin/env python
import serial
import os, sys

class MyApp:
    def __init__(self):
        port = os.environ.get('LAG_TEST_PORT', '/dev/ttyACM0' )
        self.ser = serial.Serial(port=port,
                                 timeout=0.1,
                                 baudrate=115200,
                                 )
        self.ser.open()

    def run(self):
        buf = ''
        while 1:
            buf += self.ser.read()
            if len(buf):
                buf = self._h(buf)

                #sys.stdout.write(buf)
                #sys.stdout.flush()

    def _h(self,buf):
        result = buf
        if len(buf) > 100:
            lines = buf.split('H')
            result = lines.pop()
            for line in lines:
                print '%d: %r'%(len(line), line)
        return result

if __name__=='__main__':
    app=MyApp()
    app.run()
